#!/bin/bash
# D. Racine 20171218

. $HOME/QT-env

IDS="$(idlist 15)"

PRG="$(basename $0)"

QRY="\
  set pagesize 0;
  select count(*) from employee where empstatus = 'A';"

# function: getcount id
# executes QRY on id and prints the results on a single line
getcount() {
  local CXS="$(getcxstring $1)"
  local USR="$(cut -d/ -f1 <<<"$CXS")"
  local DB="$(cut -d@ -f2 <<<"$CXS")"
  C=$(sqlplus -S -L $CXS <<<"$QRY") \
  && printf "%13s  %5d\n" "$USR@$DB" $C || echo $1 query failed; }

TMPDIR="$(mktemp -d /tmp/$PRG.XXXXXX)"

for i in $IDS; do getcount $i >$TMPDIR/$i & done

printf "%s\n%s\n%s\n\n" \
  "Active user counts extracted from production Quicktime as of" \
  "$(date) via the following query:" "$(tail -1 <<<"$QRY")"

wait; cat $TMPDIR/*; rm -rf $TMPDIR
