#!/bin/bash
# D. Racine, 20130116

. $HOME/QT-env

IDS="$(idlist 15)"

USAGE="Usage: $(basename $0) payperiod [year]"

[[ ! $1 =~ ^[0-9]{1,2}$ ]] && { printf "
  %s\n  If 'year' is omitted the current calendar year is used.\n\n" "$USAGE"; exit; }

[ "$2" ] && [[ ! $2 =~ ^[0-9]{4}$ ]] && { printf "
  %s\n  When a year is specified, it must be a 4 digit number.\n\n" "$USAGE"; exit; }

PP=$1
[ "$2" ] && YR=$2 || YR=$(date '+%Y')

STATQUERY="\
  set pagesize 0;
  set feedback off;
  select satstat2,count(*) from ppstat where ppyear = $YR and pp = $PP group by satstat2;"

# function: getstatus id
# executes STATQUERY on id and prints the results on a single line
getstatus() {
  QR="$(sqlplus -S -L $(getcxstring $1) <<<"$STATQUERY")" && {
    local UNV VER VAL CRT LCK REL
    [ $(wc -c <<<"$QR") -gt 1 ] && eval $(awk '{printf "%s=%s\n",$1,$2}' <<<"$QR")
    printf "%4s%7s%7s%7s%7s%7s%7s\n" \
           "$1" "$UNV" "$VER" "$VAL" "$CRT" "$LCK" "$REL"; } || echo $1 query failed; }

TMPBASE="/tmp/timesheet-status-$$"

for i in $IDS; do getstatus $i >$TMPBASE.$i & done

printf "\n## %s Pay Period %02s Timesheet Status\n## as of %s\n\n" $YR $PP "$(date)"
echo "  ID    UNV    VER    VAL    CRT    LCK    REL"
echo "---- ------ ------ ------ ------ ------ ------"

wait; cat $TMPBASE.*; rm -f $TMPBASE.*
