#!/bin/bash
# Prints a CL-readable list of characteristics of all QT app cluster members
# that exist on localhost. Each is represented as a list of 6 symbols:
# (|id| node-id |version| schema db running)
# where:
#   id      -> Quicktime app instance ID
#   node-id -> hostname suffix corresponding to an id in XARF's *qt-nodes*
#   version -> QT version number of cluster member
#   schema  -> schema user from cluster member's app_cfg.jpl
#   db      -> database name from cluster member's app_cfg.jpl
#   running -> boolean: t if running, nil if not
#
# D. Racine 20140910

NODE=${HOSTNAME: -3}
TMP=/tmp/xarf-qt-info.$$
FORMLIB=/qt/prolifics/util/formlib
F2ASC=/qt/prolifics/util/f2asc
AP='/^glob.*DBMS_(TA_AC|IN)/ {print $2}'

SP='s|[" \t]||g
    s|(.*)||g'

IDS="$(for j in /qt/[0-9][0-9][0-9] /qt/[0-9][0-9][0-9][0-9]; do
         [ "x$j" != "x/qt/9999" -a -d $j/web -a -d $j/srv ] \
           && basename $j; done |xargs)"

mkdir $TMP
cd $TMP
echo -n '('

for i in $IDS; do
  rm -f about.jam*
  $FORMLIB -x /qt/$i/web/client.lib about.jam
  $F2ASC -acf about.jam.asc about.jam
  VER="$(grep -om1 '[0-9]\{4\}\.[0-9]\{3\}[a-z]*' about.jam.asc)"
  eval "$(awk -F$ "$AP" /qt/$i/web/app_cfg.jpl |sed "$SP")"
  SCH="$DBMS_TA_ACCOUNT"
  DB="$DBMS_INSTANCE"
  pgrep -f "java.*qt/$i/tomee" >/dev/null && RUN=t || RUN=nil
  printf '(|%s| %s |%s| %s %s %s)' $i $NODE "$VER" "$SCH" "$DB" $RUN; done

echo ')'
cd - >/dev/null
rm -rf $TMP
