#!/bin/bash
# Uses sqlplus to extract a trans or transamend file to stdout.
# Dependencies:
#   * sqlplus
#   * getcxstring
# D. Racine 20080404

[ $# -ne 2 ] && {
  printf "\nUsage: xarf-trans app_id trans|amend\n\n";
  exit; }

. $HOME/QT-env

ID="$1"
QUERY_TYPE="$2"

# bail out if input doesn't look reasonable
[[ ! ( $ID =~ ^[0-9]{3,4}$ && $QUERY_TYPE =~ ^trans$|^amend$ ) ]] && {
  echo "Invalid parameter."; exit 1; }

DATE="$(date '+%m-%d-%Y')"
CXSTRING="$(getcxstring $ID)" || { echo getcxstring failed; exit 1; }
USER=$(cut -d/ -f1 <<<"$CXSTRING")
DB=$(cut -d@ -f2 <<<"$CXSTRING")

[ "$QUERY_TYPE" == "amend" ] && AMEND_FLAG="amend_" || AMEND_FLAG=""

QUERY="\
  set pagesize 10000;
  set linesize 180;
  select output_line from trans_output_${AMEND_FLAG}fpps
  where runtime > to_date('$DATE', 'MM-DD-YYYY')
  and runtime < to_date('$DATE-23:59:59', 'MM-DD-YYYY-HH24:MI:SS')
  order by line_order;"

echo "
  ### $QUERY_TYPE data from $USER@$DB per $ID's app_cfg.jpl ###
  "

sqlplus -L -S $CXSTRING <<<"$QUERY"
