#!/bin/bash
# D. Racine 20140721

. $HOME/WT-env


IDS="$(idlist 16)"

QRY="\
  set pagesize 0;
  select count(*) from mc_user where active = 1;"


# function: getcount id
# executes QRY on id and prints the results on a single line
getcount() {
  local CXS="$(getcxstring -t $1)"
  local USR="$(cut -d/ -f1 <<<"$CXS")"
  local DB="$(cut -d/ -f5 <<<"$CXS")"
  C=$(sqlplus -S -L $CXS <<<"$QRY") \
  && printf "%13s  %5d\n" "$USR@$DB" $C || echo $1 query failed; }


TMPBASE="/tmp/active-user-counts-$$"

for i in $IDS; do getcount $i >$TMPBASE.$i & done

printf "%s\n%s\n%s\n\n" \
  "Active user counts extracted from production WebTA as of" \
  "$(date) via the following query:" "$(tail -1 <<<"$QRY")"

wait; cat $TMPBASE.*; rm -f $TMPBASE.*
