#!/bin/bash
# D. Racine 20140211

. $HOME/WT-env

[ $# -lt 1 ] &&  { printf "
  Tests the DB schemas of the specified WebTA app instances.
  Uses 'getcxstring' to identify target schemas.\n
  Usage: testdb ID [...]\n\n"; exit 1; }


output() {
echo "tnsping_${DB}: ${TNSPING}; ${SCHEMA}@${DB}_query_result: ${QRESULT}"; }

XS=0  #gets set to 1 if any test fails

TESTQRY="\
  set pagesize 0;
  select count(table_name) from user_tables;"

while [ "$1" ]; do
  ID="$1"; shift

  CXSTRING="$(getcxstring -t $ID)" \
  || { echo "$(basename $0): getcxstring failed, skipping $ID" >&2; continue; }

  SCHEMA="$(cut -d/ -f1 <<<"$CXSTRING")"
  DB="$(cut -d/ -f5 <<<"$CXSTRING")"
  TNSPING_TRGT="$(cut -d@ -f2 <<<"$CXSTRING")"

  TNSPING="$(tnsping $TNSPING_TRGT |awk '/OK/ {print $1}')"
  [ ! "$TNSPING" ] && { TNSPING="failed!"; QRESULT="NA"; output; XS=1; continue; }

  QR=$(sqlplus -S -L $CXSTRING <<<"$TESTQRY")
  [ $QR -gt 9 ] && QRESULT="OK" || { QRESULT="failed!"; XS=1; }

  output; done; exit $XS
