#!/bin/bash
# D. Racine 20150105
# Use schlep instead of rungroovy. D. Racine 20170601

. $HOME/WT-env

PRG=$(basename $0)

usage() { printf "
  Writes a zipfile to stdout containing the results of executing
  'schlep rungroovy' with the same arguments.\n
  Usage: $PRG script.groovy [inputfile] id [...]\n\n"; exit 1; }

[ $# -lt 2 ] && usage

OWD=$PWD
TS=$(date '+%Y%m%d.%H%M%S')

GF="$(readlink -e $1)" || exit 1; shift
TD=/tmp/$PRG$$-$(basename $GF .groovy)-$TS && mkdir $TD && cd $TD || exit 1
schlep rungroovy $GF $@ >rptlog.txt 2>&1

cd ..
zip -qr - $(basename $TD)
cd $OWD && rm -rf $TD
