#!/bin/bash
# Prints a CL-readable list of characteristics of all WebTA app cluster members
# that exist on localhost. Each is represented as a list of 6 symbols:
# (|id| node-id |version| schema db running)
# where:
#   id      -> WebTA app instance ID
#   node-id -> hostname suffix corresponding to an id in XARF's *wt-nodes*
#   version -> WebTA version-build# of cluster member
#   schema  -> schema user from cluster member's server.xml
#   db      -> database name from cluster member's server.xml
#   running -> boolean: t if running, nil if not
#
# D. Racine 20140530
# Cleanup - 20140604, 20160209

VDB=~/.getver-db
NODE=${HOSTNAME: -3}

echo -n '('
for i in $(~/bin/idlist all); do
  WAR=/wt/$i/webapps/$i.war
  SXML=/wt/$i/conf/server.xml
  WAR_HASH="$(sha1sum $WAR |cut -c -40)"
  VER="$(grep -m1 $WAR_HASH $VDB |cut -c 42-)"
  eval $(grep -om1 'username=.*password=.*url=.*"' $SXML |tr \" \')
  DB="$(cut -d: -f6 <<<"$url")"
  pgrep -fo "java .*/wt/$i/.*base=/wt/$i" >/dev/null && RUN=t || RUN=nil
  printf '(|%s| %s |%s| %s %s %s)' $i $NODE "$VER" "$username" "$DB" $RUN; done
echo ')'
